apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: nagios-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nagios-core
  template:
    metadata:
      labels:
        app: nagios-core
    spec:
      containers:
        - name: nagios-container
          image: jasonrivers/nagios
          ports:
            - containerPort: 80
              protocol: TCP
              name: nagios-port
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: nagios-service
spec:
  type: NodePort
  selector:
    app: nagios-core
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
